### ISSUE TITLE
Computed writable field : setter method receive null instead of entered string 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#106]
Here is the use case : 
- Add a string property which is computed:true, delegateWritable:true to some component
- Create the setter method into the extension class. 
- Let's add a breakpoint for this method.
- Add a table view containing this property to your app
- Launch the app
- Go to the field... enter some characters and press tab (or enter)
- Go to your method breakpoint : the received value is "null" instead of your string !

NB : It fails using HTML5, but it's all right using FLEX

**Comment by vvandens** [comment]
This only happens on fields with an action map. it has nothing to do with the fact that the field is computed.
