### ISSUE TITLE
Navigation from imagePropertyView to new page

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#110]
Hello

I need to be able to raise an action while clicking on (or touching with finger) an imagePropertyView. 

My picture will take quite all the mobile device screen and will represent a car with the multiple "selectable items"... I would like the action to be able to get the click or touch position...

Then I would like that the action's context will contain the X,Y positon of the click (or touch)... and also the image position and dimension 

![gabaritvehicule](https://cloud.githubusercontent.com/assets/4968224/13981979/a324cfe4-f0e7-11e5-9b52-2f90cdfa0e7a.jpg)

**Comment by vvandens** [comment]
The action event in the context will have the width and height of the image as well as the (x,y) coordinates of the tap.
