### ISSUE TITLE
Action not raised while modifying propertyView 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#111]
It seams that the parameterized action on my propertyView is never raised.
The particularity is that the related field is a **"computed:true, delegateWritable:true"** field 

string 'ascendantStylesString', computed:true, delegateWritable:true, i18nNameKey:'pivot.style.parents'
  
propertyView name:'ascendantStylesString', action:'lovFindAncestorStyleFrontAction', actionMap:'ancestorStylesActionMap'

**Comment by vvandens** [comment]
The action is triggered _after_ the field is actually set on the model. Whenever an exception is raised, the action is not executed.
