### ISSUE TITLE
LOV table not well formatted when using text fields 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#118]
In the example bellow, the "Style" field is a "text", the values for this text field contains carriage returns.

The LOV popup displayed **a single-lines table instead of multi-line table** : 

> 
<img width="950" alt="capture d ecru 2016-04-04 a 11 03 30" src="https://cloud.githubusercontent.com/assets/4968224/14243296/f7d2c3ae-fa54-11e5-968d-d1491b600038.png">

*As soon as you select a line, the LOV table is fully re-rendered :*

> 
<img width="948" alt="capture d ecran 2016-04-04 a 11 05 34" src="https://cloud.githubusercontent.com/assets/4968224/14243330/3456fef8-fa55-11e5-89cb-53d4c9c91392.png">

**Comment by vvandens** [comment]
Certainly fixed by #117
