### ISSUE TITLE
ViewDescriptor: "Repeatable" descriptor

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#120]
We need a way to display a collecltion using grids and classic view descriptors.
Something like : 

    collectionGrid(model:'MyModel-collectionProperty', maxColumns:2) {
     form/table/grid/border/... (model:'CollectionPropertyElementDescriptor) {
      ...
      }
    }

On a collection with 6 elements, would render something that sould look like:

    grid(model:'MyModel-collectionProperty') {
    	cell(row:0, column:0) {
    		form(model:'MyModel-collectionProperty[0]')
    	}
    		cell(row:0, column:1) {
    		form(model:'MyModel-collectionProperty[1]')
    	}
    		cell(row:1, column:0) {
    		form(model:'MyModel-collectionProperty[2]')
    	}
    		cell(row:1, column:1) {
    		form(model:'MyModel-collectionProperty[3]')
    	}
    		cell(row:2, column:0) {
    		form(model:'MyModel-collectionProperty[4]')
    	}
    		cell(row:2, column:1) {
    		form(model:'MyModel-collectionProperty[5]')
    	}
    }

**Comment by vvandens** [comment]
We have introduced an new repeater collection view which supports selection action and row action.
For instance :

```
repeater ('Company-departments.repeater', actionMap: 'masterDetailActionMap') {
  repeat {
    border (model: 'Department') {
      north {
        form(fields: ['name', 'ouId'])
      }
      south {
        table(model: 'Department-teams', columns: ['name', 'ouId'], preferredHeight: 200)
      }
    }
  }
}
```
