### ISSUE TITLE
Do not display workspace for small jspresso app

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#125]
When there is only one single workspace available for current user, do not display the workspace :
- No accordion for desktop app 
- For mobile app, let's go directly to workspace's module list immediately after the login (without any visual transition to completely hide the workspace, and do not allow to go back to workspaces list)

**Comment by maximehamm** [comment]
NB : Let the developer decide whether or not activate this mechanism !

**Comment by vvandens** [comment]
#166 supersedes this one
