### ISSUE TITLE
Mobile "item selection action" not re-activated when going back to mobileListView

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#127]
Here is the use case :
- A *mobileListView's* having an "itemSelectionAction" which is opening a dialog 
- Pressing an item : the dialog opens.
- Closing the dialog : the dialog closes. We're back to the list.
- Press again *the same* item : *the action is not activated* !

**Comment by vvandens** [comment]
What you need is the rowAction not the itemSelectionAction. The former is executed every time whereas the second one is only executed when the selection changes.
