### ISSUE TITLE
Decimal property using BigDecimal fail with default value by trying to affect a Double

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#131]
Using a property of type decimal with a useBigDecimal:true the component initialization tries to affect a Double to the property leadign to classCastexception.

![image](https://cloud.githubusercontent.com/assets/11617325/14642179/bbb57f28-0649-11e6-96bb-0d020085d6e6.png)

**Comment by vvandens** [comment]
It only happens when usingBigDecimal is set _after_ defaultVaue
