### ISSUE TITLE
Two lines of text for mobile action 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#146]
To allow to setup a slightly longer text for action's label, **use two lines for button labels**... 
But only if there is no icon to display so that the button height will remain the same as today
1 icon + 1 line of text 
or 
No icon + 2 lines of text

**Comment by maximehamm** [comment]
Please, report this enhancement in 4.2.X !

**Comment by vvandens** [comment]
fixed by commit e88db9cb29ae4c81c65dbe48396246b2a7398924
