### ISSUE TITLE
HTML property's action

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#148]
Today the `action` property seems to have no effect when used for a `htmlPropertyView`.
Please add the support of it.

Of course the framework should **not force the underlying** of the property text.

In line with this, it would be great to **only activate the hyperlink where the user would have explicitly set a pseudo-url**. 

The icing on the cake is that we should be able to **add some parameters to the action's context** using the pseudo-url.

**Comment by vvandens** [comment]
All points are implemented.
the syntax for passing a string parameter to the action context as the action command is :
`<a href='executeAction("param")'>link value</a>`

**Comment by maximehamm** [comment]
This is fine to manage hyperlink inside html text to launch Jspresso action !
