### ISSUE TITLE
SJS to Spring generation: Bad Spring definition when setting inline next attribute to null

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#152]
action('addVinOperationToPreloadFrontAction', parent:'lovOkFrontAction', next:null) {
  wrapped(class:'fr.gefco.tom.frontend.action.AddVinOperationToPreloadFrontAction')
}

  <bean
    id="addVinOperationToPreloadFrontAction"
    parent="lovOkFrontAction">
    <property
      name="permId"
      value="addVinOperationToPreloadFrontAction" />
    <property
      name="wrappedAction">
      <bean
        class="fr.gefco.tom.frontend.action.AddVinOperationToPreloadFrontAction">
      </bean>
    </property>
  </bean>

**Comment by vvandens** [comment]
implemente in SJS 2.6-SNAPSHOT
