### ISSUE TITLE
PreferredWidth is ignored for table image property view 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#154]
The preferredWidth is ignored when using `image` property :

```
table (model:'Team-teamMembers', horizontallyScrollable:false) {
    columns {
        image name:'photo', scaledHeight:25, preferredWidth:50
        propertyView name:'fullName'
    }
}
```

**Comment by vvandens** [comment]
Could not reproduce. Are you sure that the column width was not saved in the user preference ? In that case, it is restored independently of the column preferred width value.

**Comment by maximehamm** [comment]
Que dalle ! Regarde la colonne photo ci-dessous dans HR EE, la largeur est ignorée :

table (model:'Team-teamMembers', borderType:'NONE', horizontallyScrollable:false, preferredHeight:120) {
              actionMap {
                actionList('EDIT') {
                  action(parent: 'pickupAndAddAnyFrontAction', custom: [entityDescriptor_ref: 'Employee', initializationMapping: ['company':'company']])
                  action(ref: 'removeAnyCollectionFromMasterFrontAction')
                }
              }
              columns {
                image name:'photo', scaledHeight:25, preferredWidth:50
                propertyView ref:'Employee-fullname.property'
              }
            }

**Comment by maximehamm** [comment]
Problem is still present... The example above is the

**Comment by maximehamm** [comment]
Problem stills occurs... Please see `photo` property in 
the example below from HRSample EE :

```
table (model:'Team-teamMembers', borderType:'NONE', horizontallyScrollable:false, preferredHeight:120) {
              actionMap {
                actionList('EDIT') {
                  action(parent: 'pickupAndAddAnyFrontAction', custom: [entityDescriptor_ref: 'Employee', initializationMapping: ['company':'company']])
                  action(ref: 'removeAnyCollectionFromMasterFrontAction')
                }
              }
              columns {
                image name:'photo', scaledHeight:25, preferredWidth:50
                propertyView ref:'Employee-fullname.property'
              }
            }
```

![pastedgraphic-12](https://cloud.githubusercontent.com/assets/4968224/15601432/8c01b4f4-23ef-11e6-949d-f371ddde33d1.png)
