### ISSUE TITLE
Action map buttons visible or not depending on gate state

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#161]
Hi
Is it possible to manage to **hide** action buttons instead of shade it ?
It would be nice to setup "hideWhenDisabled:true" on actions / action lists / action maps
Thx

**Comment by vvandens** [comment]
A new property `hideActionWhenDisabled` is available on actionMap and actionList.
A new property `hiddenWhenDisabled` is available on action.
