### ISSUE TITLE
Description in mobile workspace

### ISSUE THREAD

**Issue by anassben** [jspresso/jspresso-ce#169]
Even if  we don't put attribute 'description' in workspace, it appears as even below the name of the workspace 'Description...'

**Comment by vvandens** [comment]
In case you want an "empty" description on a workspace or a module, you must use an empty translation in the resource bundle, e.g. :
```
MyWorkspace.description=
MyModule.description=
```
If you simply do not have the keys above in the application resource bundle, then the framework will use the dot notation to determine a fallback translation key, which is "description" in that case.
