### ISSUE TITLE
Random behavior for date_time properties when value is entered

### ISSUE THREAD

**Issue by Ygor-YC** [jspresso/jspresso-ce#176]
In a table, often for the 1st row, I enter a date and when I leave the field, either by Enter or by Tab, the field is blank.
Qooxdoo GUI, jspresso 4.3

**Comment by vvandens** [comment]
Do you observe this behavior only for date/time fields or also for plain date fields ?
Until now I couldn't reproduce. Do you exclusively use the keyboard to validate the entered value in the field (tab or enter) ? What is your platform ? browser ?

**Comment by Ygor-YC** [comment]
I observe this for date_time only, when I leave the field either by tab or enter.
I tried to leave with the mouse : in this case the behavior is correct.
Platform : Windows 7, Windows 10
Browser : Chrome 53.0.2785.101, Firefox 48.0.2
