### ISSUE TITLE
Dynamic foreground, background, labelForeground, etc.

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#179]
Hello

The use of dynamic UI properties doesn't work very well :

- **background** : **KO** for **boolean** (FLEX) and **enumeration** (FLEX) Properties. **KO** for **forms**
- **foreground** : **KO** for all kind of properties (FLEX - HTML5)
- **font** : OK 

For labels :
- **labelBackground** : KO
- **labelForeground** : KO
- **labelFont** : KO & Crash : "Font string representation must be formed as [name];[style];[size]"

**Comment by vvandens** [comment]
label colors are not dynamic.
