### ISSUE TITLE
Forms background colors sinks into fields (HTML5)

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#180]
When setting a background color for a form, the property fields in it are also filled with the colors :
- string, text...
- enumeration
- decimal...

NB : it is fine using FLEX

![capture d écran 2016-09-12 a 09 59 52](https://cloud.githubusercontent.com/assets/4968224/18428717/ddba1df6-78cf-11e6-8a78-4aeedc6c6a35.png)

![capture d écran 2016-09-12 a 10 00 25](https://cloud.githubusercontent.com/assets/4968224/18428720/e01e54b8-78cf-11e6-8df2-62a3f0e10f93.png)

**Another little issue** : a tiny border appears wich is not beautiful :
- surrounding forms (even if bordeType:'NONE' is set)
- surrounding some field (see first screenshot above)

![capture d ecran 2016-09-12 a 10 03 04](https://cloud.githubusercontent.com/assets/4968224/18428769/352f964c-78d0-11e6-9c07-5e810ba1d838.png)

![capture d ecran 2016-09-12 a 10 03 24](https://cloud.githubusercontent.com/assets/4968224/18428770/3699257a-78d0-11e6-8f25-a54158276bb5.png)

**Comment by vvandens** [comment]
This is linked to dynamic background colors being incorrectly computed in HTML5. See #179
