### ISSUE TITLE
LOV property view background is drooling over form's background

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#194]
Here is an example : the property's gray background is drooling over form's blue background

<img width="1027" alt="capture d ecran 2016-10-12 a 20 12 38" src="https://cloud.githubusercontent.com/assets/4968224/19322260/96dd8f16-90b8-11e6-991e-7604be92b772.png">

**Comment by maximehamm** [comment]
With HTML5 it is not the same problem : the color is not drooling far away... but it is not limited to the string part of the LOV property as expected

<img width="1212" alt="capture d ecran 2016-10-12 a 20 22 56" src="https://cloud.githubusercontent.com/assets/4968224/19322532/ba8934c8-90b9-11e6-9b0d-29a46161e02c.png">

**Comment by vvandens** [comment]
Fixed by commit #89607e698b1c67a4846bb30292dfc4a1e7dfdb28
