### ISSUE TITLE
Add the capability to copy cell table value into the clipboard

### ISSUE THREAD

**Issue by W-Alphonse** [jspresso/jspresso-ce#208]
Please add the capability to copy a "cell value" or an "entire line values" from a table view into the clipboard. (HTML5 / 4.2.9-SNAPSHOT).
Thank you.

**Comment by vvandens** [comment]
The user can now select the text displayed in a table cell in order to CTRL-C it.

**Comment by vvandens** [comment]
Does not work in Firefox.
Chrome allows selection but CTRL deselects
