### ISSUE TITLE
The cloneModuleObjectFrontAction is not working

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#230]
This action is not correct :
`  <bean id="cloneModuleObjectFrontAction" parent="cloneEntityCollectionFrontAction" />`

It should be :
```
<bean id="cloneEntityCollectionFrontAction" parent="cloneEntityCollectionFrontAction">
    <property name="wrappedAction">
      <bean class="org.jspresso.framework.application.backend.action.CloneComponentAction">
        <property name="entityCloneFactory" ref="smartEntityCloneFactory" />
      </bean>
   </property>
</bean>
```

(The wrapped class is "_org.jspresso.framework.application.backend.action.CloneComponentAction_" not "_org.jspresso.framework.application.backend.action.CloneComponent**Collection**Action_")

**Comment by vvandens** [comment]
I can't see this definition. The one that is in the 4.3, 4.2.x and 4.2.9.x is correctly wrapping the `CloneComponentCollectionAction`. Could you double-check please ?
