### ISSUE TITLE
jspresso-qooxdoo-client packaging

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#254]
This packaging should be set to zip.
Being set as "pom" cause issues when trying to use maven-deploy-plugin to deploy this. Only pom is deployed.

<parent>
    <groupId>org.jspresso.framework</groupId>
    <artifactId>jspresso-root</artifactId>
    <version>4.2.9.8.5</version>
    <relativePath>../../root/pom.xml</relativePath>
  </parent>
  <artifactId>jspresso-qooxdoo-client</artifactId>
  <packaging>pom</packaging>
  <name>Qooxdoo - Client</name>

**Comment by Dealus** [comment]
As well as for jspresso-qooxdoo-theme

**Comment by vvandens** [comment]
What kind of issue do you observe ? It has always been pom packaging and the zip is attached as a side artifact built by the assembly plugin.
see http://repository.jspresso.org/maven2/org/jspresso/framework/jspresso-qooxdoo-client/4.2.9.8.5/
