### ISSUE TITLE
Control collapsable modules state

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#262]
A Boolean startCollapsed property for Module would prove useful to have a cleaner application on startup when the hierarchy of modules become complex.

It should also be possible to collapse/uncollapse modules programmatically using the frontendController.

**Comment by vvandens** [comment]
a new property `expanded` has been declared on the `Workspace` object. In order to use it, you must switch to SJS 2.6-SNAPSHOT
