### ISSUE TITLE
Icon format: Indexed colored icons crash

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#263]
The java.io.Image.rotate() function does NPE when the given image has its colors indexed.
Some other more robust library should be use to handle icons.

It's quite hard to figure out what's the problem (I had to compare the image metadata with some of the framework's images using Gimp...)

**Comment by Dealus** [comment]
Here are samples:

Indexed colors, not working:
![check-mark](https://cloud.githubusercontent.com/assets/11617325/24140846/c6046cce-0e21-11e7-8bf7-0ba420d87ea9.png)

**Comment by vvandens** [comment]
This is a known problem with the ImageIO jdk library when working (like resizing) with indexed color PNG that use transparency. The transparency is lost, resulting in a black background.
