### ISSUE TITLE
Default entity view

### ISSUE THREAD

**Issue by pmbjs** [jspresso/jspresso-ce#279]
It could be interesting to be able to setup a default view for each Entity.
Currently the default view is automatically generated by Jspresso.

**Comment by vvandens** [comment]
The controller now accepts a `defaultViews`property which is a map in the form :
`[EntityName:'ViewName']`

**Comment by vvandens** [comment]
After more thinking about it, we agreed that it is pretty useless to have such a feature. The views will always be customized even if they have the same model and we can always centralize things through inheritance. So we will rollback this change.
