### ISSUE TITLE
Computed fields are shrinked when displayed on html5

### ISSUE THREAD

**Issue by Ygor-YC** [jspresso/jspresso-ce#28]
The html5 screen below shows a computed field that is shrinked :
![image](https://cloud.githubusercontent.com/assets/12913065/8185880/2c877012-1447-11e5-8113-14d09637d3a1.png)

on flex, it is ok :
![image](https://cloud.githubusercontent.com/assets/12913065/8185942/79481ad2-1447-11e5-9f03-483300564772.png)

**Comment by vvandens** [comment]
Unfortunately, I cannot reproduce the problem. Could you please ensure you reproduce it with the latest `4.1.2` release (`<jspresso.version>4.1.2</jspresso.version>` in your root `pom.xml`) ?
