### ISSUE TITLE
Capability to move binary property actions anywhere

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#288]
I would like to move actions owned by "binaryPropertyActionMap" some where else inside my UI...
I would like to be able to add some parameter as "custom" of each action to be able to set a "path" from current view's model to the binary property view's model... 
For example :
actionList {
    action parent: 'openFileAsBinaryPropertyAction', custom:[path:'company.logo'] 
    action parent: 'resetPropertyFrontAction', custom:[path:'company.logo']
}

**Comment by vvandens** [comment]
The property is called `modelPath` and is available on all 4 binary property actions.
