### ISSUE TITLE
DependsOn... Collection

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#290]
Please add a second annotation, named for example "DependsOnCollection" so that we will be able to set both dependency about properties and about collection's properties... 
(i.e repeated annotation is not supported before Java 8)

**Comment by vvandens** [comment]
The implemented solution introduces a new annotation that is able to group multiple DependsOn annotations, thus working around the limitation, e.g.:

```
  @DependsOnGroup({
      @DependsOn(Employee.FIRST_NAME),
      @DependsOn(Employee.NAME)
  })
```
