### ISSUE TITLE
[Table] : Column characteristic (hidden by default)

### ISSUE THREAD

**Issue by GefMetis** [jspresso/jspresso-ce#318]
Currently, column order, width and hidden status are stored for each user.
Would it be possible to have a table where a set of column is by default hidden (at the first connection).
Similarly, would it be possible to have the column width set to a certain value ?

**Comment by vvandens** [comment]
It's actually already possible.
By defining a `preferredHeight` to any negative value on a table column, it will appear initially hidden.
Defining a `preferredWidth` on a column will also size it accordingly.
