### ISSUE TITLE
createEntityFromLovOkAction don't select created item

### ISSUE THREAD

**Issue by bvo** [jspresso/jspresso-ce#331]
in the lovActionWithCreate popup, the creation stop the process before select the created item in the parent list, so if the user click on OK, the addAnyToMasterFrontAction don't have select item and bug.
I think addAnyToMasterFrontAction must be more tolerant, no item = no action but no bug
And lovActionWithCreate would select the created item in the parent list

action('addFromList', parent:'lovOkFrontAction') {
    next(parent:'addAnyToMasterFrontAction')
}

actionMap('eventAddRemoveTableActionMap') {
    actionList('EDIT') {
        action parent: 'lovActionWithCreate',
                custom:[
                        'autoquery':true,
                        entityDescriptor_ref:'MyEntity',
                        okAction_ref:'addFromList',
                        selectionMode: 'MULTIPLE_INTERVAL_CUMULATIVE_SELECTION'
                ], name: 'choose'
        action ref:'removeAnyCollectionFromMasterFrontAction'
    }
}

**Comment by vvandens** [comment]
I've just checked The lovActionWithCreate on the latest Jspresso framework (5.1.10) and the item is correctly selected when created.
Closing
