### ISSUE TITLE
Image iconWidth and iconHeight issue for SVG

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#337]
SVG images dimension is not working 
- neither from model side nor from view side 
- neither using 'image' nor 'imageUrl'
- neither using 'propertyView' nor 'image'

**Comment by vvandens** [comment]
Do not use `iconWidth` and ìconHeight` on image and `imageUrl` properties and property views. They are use to tune the icon size of the view not the image size itself. to achieve that, use the `scaleWidth` and `scaledHeight` attributes.
