### ISSUE TITLE
Initialization mapping not performed

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#342]
Hello

The initialization mapping is not launch in this particular case (i.e second component is generated by the framework)

```
 Component('UserQueryUIItem') {

        reference 'part1', ref: 'UserQueryUIItemPart', mandatory: true, initializationMapping: ['position': 0]
        reference 'part2', ref: 'UserQueryUIItemPart', mandatory: true, initializationMapping: ['position': 1]
    }

    Component('UserQueryUIItemPart') {
        integer 'position'
        string 'label', computed: true
    }

```

**Comment by vvandens** [comment]
reference initialization mapping is used only in LOVs when constructing the LOV filter. It's not a general purpose default value for Entity / component creation. You should use a lifecycle `onCreate` interceptor instead.
