### ISSUE TITLE
MyQueries view tuning

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#344]
There is too many white space between lines in the "My queries" view. 
It should be the same interleave than between two lines of a standard formular.
![capture d ecran 2017-11-20 a 15 32 55](https://user-images.githubusercontent.com/4968224/33023366-2c54f1fa-ce08-11e7-9b3f-85bc79afcbb7.png)

**Comment by vvandens** [comment]
Having space is not so bad...
