### ISSUE TITLE
MapView point icons

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#354]
Please choose a catch-all icon for map points instead of this "church" icon ?
BTW, is it possible to customize point styles programmatically :
- Icon url
- Icon size
Allow to apply a different style for each point

**Comment by vvandens** [comment]
The markers entry in the map json now supports the following syntax :
markers : {
  coord: [x,y],
  image: {
    src: "anyImageURL"
  }
}

Moreover, the image entry supports all the entries defined here (opacity, anchor, ...) :
https://openlayers.org/en/latest/apidoc/ol.style.Icon.html
