### ISSUE TITLE
Wrong property view alignement with setting font size

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#356]
The property's label is not at same height as the property value 
![capture d ecran 2017-11-27 a 00 46 15](https://user-images.githubusercontent.com/4968224/33245778-66d15892-d30c-11e7-8c79-ab526778a7de.png)

**Comment by vvandens** [comment]
Could not reproduce... The various fields are correctly aligned in the form (everything is centered vertically)

<img width="1040" alt="layout" src="https://user-images.githubusercontent.com/832886/34382988-b0225ae6-eb12-11e7-8189-4f4173c07dc6.png">
