### ISSUE TITLE
Popup message max size

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#367]
When a message popup is open, the width and height should not exceed the browser UI size

It is no more possible to click "ok" or "cancel" !

**Comment by maximehamm** [comment]
It is not working well...

See example bellow : click on "export to Tmar" from HRSample's companies module :

<img width="1500" alt="sans titre" src="https://user-images.githubusercontent.com/4968224/34014075-2270ab96-e11a-11e7-83c1-13121dd94720.png">

**Comment by vvandens** [comment]
Could not reproduce the issue. Please check that you correctly recompiled the whole application with the fixed version.
