### ISSUE TITLE
Improvement liveDebugUI

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#377]
Please 
- Let the "liveDebugUI" be updated programmatically for the active session
- Let implement some "LiveDebugDelegate" in charge of rendering tooltips when the "liveDebugUI" is true

**Comment by maximehamm** [comment]
One more thing : let the invoked method be aware of related view connector... so that the delegate will be able to display informations about the data and the UI...

**Comment by vvandens** [comment]
You can now implement the `org.jspresso.framework.view.IUIDebugPlugin` interface and inject it into the context under the name `liveUIDebugPlugin`

**Comment by vvandens** [comment]
Moreover, `liveDebugUI` can now be enabled dynamically on a session frontend controller.
