### ISSUE TITLE
Lov action popup : label on ok, cancel and find actions

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#378]
Please remove the "`<property name="name"><null/></property>`" to let those actions to follow what is specified into "`viewFactoryBase`" and "`defaultActionMapRenderingOptions`"

**Comment by vvandens** [comment]
Dialog actions do not follow the `defaultActionMapRenderingOptions`.
However, we've restored the labels on LOV dialog actions.
We've also made 1st level beans for LOV dialog actions customisations (label, icon, ...) :
```
  <bean id="lovOkFrontAction" parent="lovOkFrontActionBase"/>
  <bean id="lovCancelFrontAction" parent="lovOkCancelActionBase"/>
  <bean id="lovFindFrontAction" parent="lovFindFrontActionBase"/>
```
