### ISSUE TITLE
Mobile item selection action is called once only 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#389]
When clicking the line, the "openAttachementAction" is raised... but NOT the second time or the time after...

    ```
    mobileNavPage (readOnly: true) {
            selection {
                mobileListView(model:'Issue-attachments',
                        rendered: 'htmlMobileDescription', 
                        itemSelectionAction: 'openAttachementAction')
            }
        }
```

**Comment by vvandens** [comment]
You should use `rowAction` instead of `itemSelectionAction`. Once an item is selected, clicking on it does not change the selection thus not trigger the action.
