### ISSUE TITLE
Bug getSelectedModelsFromPermId and others

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#401]
When no view if found for given permId (i.e getViewPathFromPermId return null), the method should return null...
But it is returning the current model (i.e like if viewPath was int[Ø]

Same issue for other getXxxxFromPermId

**Comment by maximehamm** [comment]
Hello
The evolution causes to much regression... when using the getViewPath(null, context)... before the return value was the current view... now it returns null... and causes null pointer...

   public static <T> IView<T> navigate(IView<T> fromView, int... viewPath) {
 +    if (viewPath == null) {
 +      return null;
 +    }

**Comment by vvandens** [comment]
Why would you use `getViewPath(null, context)` instead of `getViewPath(context)` ?

**Comment by vvandens** [comment]
However, we can use a magic constant for the case where a non-null viewPath has been asked and was not found. This should solve the problem...

**Comment by vvandens** [comment]
Can you test the new fix ?
The FW will return a null view if and only if a invalid permId has been given. Passing a null view path should return the current view as before.
