### ISSUE TITLE
Let AbstractActionContextAware.getViewPathFromPermId() be public

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#402]
This method is useful (and needed) if we want to find a view for example using the permId for a view which is not the current view

(Urgent please 😬)

**Comment by vvandens** [comment]
Helper methods transferred to a new helper class :
`org.jspresso.framework.application.view.ViewHelper`

**Comment by vvandens** [comment]
There was already a `org.jspresso.framework.view.descriptor.basic.ViewHelper` class... Removed the newly created `org.jspresso.framework.application.view.ViewHelper` and transferred the new helper methods to the existing one.
