### ISSUE TITLE
Form's "staticText" issues

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#403]
The "staticText" field is not working well :

- The i18n is using "i18nNameKey" instead of "i18nTextKey" a documented (I think you should remove i18nTextKey)
- The "labelForeground" does not work... neither "foreground"
- The "labelHorizontalPosition" does not work... neither "horizontalPosition"

You should check also if "background" and other attributes...

**Comment by maximehamm** [comment]
Here is an example :

```
form (model: 'CFilterQuotation', columnCount:4) {
                    fields {
                        staticText i18nNameKey: 'flows', i18nTextKey: 'flows', labelFont: ';BOLD;16', width:20,
                                labelForeground: '0xFF003875', foreground: '0xFF003875',
                                labelHorizontalPosition: 'LEFT', horizontalAlignment: 'LEFT'

                        propertyView name: 'filterDepAddress', labelHorizontalPosition: 'LEFT'
                        propertyView name: 'filterArrAddress'
                        propertyView name: 'filterMark1', icon:'classpath:org/jspresso/framework/application/images/flags-48x48.png', i18nNameKey: 'empty.string'
                    }
                }
```

![sans titre](https://user-images.githubusercontent.com/4968224/34292032-6cce741c-e6ff-11e7-813a-2d9772c737f2.png)

**Comment by vvandens** [comment]
Could not reproduce. Everything works fine here...
