### ISSUE TITLE
Action on staticText is not working 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#405]
Unable to setup an action onto a staticText field (i.e no hyperlink is available)

```
form(columnCount:1) {
    fields {
        staticText i18nTextKey: 'export.all', action: 'muExportAllDataFrontAction'
    }
}
```

**Comment by vvandens** [comment]
Will check this one.
However, do you remember that you can trigger actions in using HTML hyperlinks ?
see https://github.com/jspresso/jspresso-ce/issues/148
