### ISSUE TITLE
Creating new records through the LOV

### ISSUE THREAD

**Issue by wagner-wutzke** [jspresso/jspresso-ce#41]
This is a enhancement request as described in http://stackoverflow.com/questions/32148667/create-new-records-when-searching-for-reference-object/32272285#32272285.
I would like to be able to create new objects when searching for a reference object in a given LOV.
As Vincent V. said "this kind of behavior might very well find its way to the framework".
Thank you very much!

**Comment by vvandens** [comment]
The standard LOV action now supports a `createAction` property. A new standard bean with a default implementation as described in the SO question has been created under the name `lovActionWithCreate`. You can reference it reference field per reference field or use it globally in your application using the following one line statement :

```java
action('lovAction', parent: 'lovActionWithCreate')
```

**Comment by wagner-wutzke** [comment]
This is awesome!
Great feature in my opinion.
Thanks a lot!
