### ISSUE TITLE
MapView segment style

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#413]
Let customize segment lines : color, continuous or stippled, thickness 
Let do that segment per segment

**Comment by vvandens** [comment]
The routes entry now supports the following syntax to define a route style :

```
routes: [
  {
    path: [[x1,y1],[x2,y2],[x3,y3]],
    style: {
      color: "#123456",
      width: 2
    }
  },
  {
    path: [[x'1,y'1],[x'2,y'2],[x'3,y'3]],
    style: {
      color: "#654321",
      width: 4
    }
  }
] 
```

Moreover, the style entry supports all the parameters defined here :
https://openlayers.org/en/latest/apidoc/ol.style.Stroke.html
