### ISSUE TITLE
Filter module inheritance is KO

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#448]
Here is the use case
- Create a module 'a'
- Create two workspace with a module `b parent:'a'`

At run time the second workspace's module looks like the first one... 

NB : Issue using mobile app (desktop to be tested also)

**Comment by maximehamm** [comment]
In fact the problem is that both modules use the same id...

**Comment by vvandens** [comment]
We can easily do that, but there are plenty of cases when it's ok to just import a module (from a lib for instance) without having to redefine an ID. I would rather let it like that and raise a warning on the plugin if 2 modules have the same id (either direct or inherited from its parent)
