### ISSUE TITLE
Avoid recursion while using table selection model

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#452]
I have a problem to synchronize multiple tables selection each other... 

I have 5 tables and an unfair model... I decided to use an "itemSelectionAction" to be able to manage the synchronization logic at a single point.

The problem is that the "itemSelectionAction" is called recursively... 
I need to get something from the action's context to know if the action is triggered due to a humain action or due to recursion.

Please help, I'm stuck !

**Comment by vvandens** [comment]
Make sure that `autoSelectFirstRow` is set to false on your tables
