### ISSUE TITLE
Unable to reconnect to jspresso mobile

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#479]
While debugging my jspresso mobile app using chrome... I often face difficulties to reconnect to the app... for example after a session timeout... I try to refresh the browser tab... but the UI remain blank... 

I found a workaround : opening another browser tab... logon using the desktop interface (sic!) ... logging out... going back to the mobile app tab... and refreshing it... It works again !

Any suggestion ?

**Comment by maximehamm** [comment]
Normal web page

Envoyé de mon iPhone

**Comment by vvandens** [comment]
Cannot reproduce...
