### ISSUE TITLE
Service card view

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#519]
Here is a new strategy to manage card content : using a model service

Here an example :

```
serviceCardView('Employee.view', 
        service: 'getGender', 
        defaultView: 'Employee.nogenderDefined.view',
        views:[ 'men': 'Employee.men.view',
                'woman' : 'Employee.woman.view'])
```

The `getGender` service is a public method having no parameter or a single parameter which is a `Map<String, Object>`. Here possible values are `men`, `women` or `null`. 

Let's also support inlined definition :

```
serviceCardView('Employee.view', 
       service: 'getGenre') {
    defaultView {
          form(model:'Employee', fields:['fistName', 'lastName', 'gender']
    }
    views {
        form('men', model:'Employee', fields:['fistName', 'lastName', 'gender']
        form('woman', model:'Employee', fields:['fistName', 'lastName', 'gender', 'maidenName']
    }
}
```

If model is `null`, display the `defaultView` (as read only) if exists, or nothing if not.
If service returns none of expected values, display the `defaultView` if exists, or nothing if not.

Let's support service return values :
- the `null` value
- `String`, `Integer` and `Boolean` values
- `Collection` and arrays, thinking `null` if collection/array is null or empty (default view will be used instead)
- Any other value type, think `null` if value is null (default view will be used instead)

 **NB : Icing on the cake, refresh according service's `dependsOn` annotation**

**Comment by vvandens** [comment]
Implemented a `propertyCardView` with a `property` attribute that should return the card name. When the property changes, the card view is refreshed automatically. The context is not available when changing the view model so it's not possible to use a service with a context parameter.
Moreover, I don't get the use of the defaultView, so it's not implemented. If there is a real justification, then it should be implemented for all card views... Then open a separate RFE for that.
