### ISSUE TITLE
[Firefox] : Text selection in a table

### ISSUE THREAD

**Issue by GefMetis** [jspresso/jspresso-ce#520]
Text is unwillingly highlighted when slecting a line of a populated table.
It seems to be a Firefox dependent bug.
![image](https://user-images.githubusercontent.com/32517788/39930642-8f029e1e-553b-11e8-8566-036b0a823824.png)

**Comment by vvandens** [comment]
This is tightly linked to the browser implementation... Will have to wait for a fix from Firefox
