### ISSUE TITLE
Mobile filter module : header description does not produce expected result

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#529]
When setting a "header description" for a filter module, the header is visible above filter view...
It should be visible above in the page which displays all workspace's modules... above the module name.
I.E like "header description" for a workspace is visible above the workspace name in the page which displays all workspaces.

**Comment by vvandens** [comment]
module `headerDescription` has been changed to `pageHeaderDescription` since it is leveraged as a page header.
Modules `description` are now correctly leveraged.
