### ISSUE TITLE
Mobile form's title is still visible whenever its boolean readability gate is closed

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#535]
Here is the code :

```
        mobileForm (borderType: 'TITLED', name: 'SAP.details', booleanReadabilityGates: ['sapKey']) {
            fields {
                propertyView name: 'sapKey'
            }
        }

        ...
```

Here is the UI :
![image](https://user-images.githubusercontent.com/4968224/40718625-fed0bab2-6410-11e8-8039-3e0f17f55249.png)

**Comment by maximehamm** [comment]
Much better... but still a little rendering thing to fix : the line separator between properties is too thick :

![image](https://user-images.githubusercontent.com/4968224/40826241-68d52ce4-657a-11e8-9f3a-1ff9025d93b1.png)

**Comment by vvandens** [comment]
It's not this one
