### ISSUE TITLE
Mobile form's title is not dynamic 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#541]
Please let's do as desktop forms

**Comment by vvandens** [comment]
Fixed

**Comment by maximehamm** [comment]
No title displayed :( 

```
mobileForm('ThirdPartyRequestEventQuestion.view', labelsPosition: 'NONE',
        name: 'title') {
    fields {
        propertyView name: 'message'// Single line question
    }
}

```

![image](https://user-images.githubusercontent.com/4968224/40826384-c28285e8-657a-11e8-84af-a012e9ebce0e.png)

**Comment by vvandens** [comment]
what is the value of border ?

**Comment by maximehamm** [comment]
Heu... "borderType:true" 

It is working when the mobile view is part or a mobile composite page... but it does not work here... it is the view used by a Jspresso's "edit component action"....

**Comment by maximehamm** [comment]
Just a confirmation after debugging inside MobileEditComponentAction : the view descriptor's title is a border type... But it is never displayed...

**Comment by vvandens** [comment]
I bet your action does not inherit from MobileEditComponentAction...
