### ISSUE TITLE
Hibernate exception "Duplicate entry"

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#566]
Here is the code : 

```
Entity('FlowSet') {
    set 'currencies', ref: 'TCurrency', processors: ['CurrenciesProcessor'], composition: true
}

Entity('TCurrency') {
    reference 'flowSet', ref:'FlowSet', reverse:'FlowSet-currencies', unicityScope: 'tenderCurrency'
    reference 'currency', ref: 'Currency', unicityScope: 'tenderCurrency'
}

Entity('Currency')
```

Here is the use case : 
- Create a FlowSet and save it
- Create a TCurrency. Link it to "GBP" Currency
- Save 
- Create another TCurrency. Link it to "GBP" Currency too
- Delete the first created Currency
- Save 
--> Hibernate error : Duplicate entry 'xxxx' for key 'TENDER_CURRENCY_UNQ'

**Comment by vvandens** [comment]
There is no way for the framework to know wether suppressions must be done before or after insertions... So you have to custom code it using a transaction.
