### ISSUE TITLE
Persisting a computed property

### ISSUE THREAD

**Issue by Ygor-YC** [jspresso/jspresso-ce#57]
Sometimes, for optimization purposes or new functionnal rules, we have to persist a property that was formerly defined as computed.

The common way to transform a computed property  into a new persisted one, is to define a processor on every property related to the computed and then calling a method in order to recompute and update the new persisted property.

**It would be very convenient to move the method into the ServiceDelegate and annoting (like @DependsOn ?) this method with the list of its dependent properties.
In this way, the method is fired every time one of its dependent property is changed.**

**Comment by maximehamm** [comment]
NB : The "DependsOn" has to be set into the Service class (i.e not the service delegate)
