### ISSUE TITLE
title is collapsed by default

### ISSUE THREAD

**Issue by GefMetis** [jspresso/jspresso-ce#607]
The request would be : having the possibility to have collapsable areas with a title collapsed by default.

For instance, an advanced settings menu would be hidden by default.

![git](https://user-images.githubusercontent.com/32517788/45371769-a7165200-b5eb-11e8-87c8-eac257202748.JPG)

**Comment by vvandens** [comment]
Added a collapsed:[true|false] property on every view that is collapsible.
Requires SJS 4.0.0-SNAPSHOT until  release is available.
