### ISSUE TITLE
Tree not well rendered

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#618]
Multiple little issues :
- expanded:true, collapsed: false : Tree is style collapsed
- collapsible:false : Tree expended button are still visible
- icon : no effect
- background : no matter

Here is code sample :
```
tree('BusinessLine.tree', rendered: 'description', expanded: true, icon: 'svg/diagram-1.svg', displayIcon: true) {
    subTree('BusinessLine-businesses.treeNode') {
        subTree('Business-activities.treeNode')
    }
}

treeNode('BusinessLine-businesses.treeNode', rendered: 'businessId',
        icon: 'svg/diagram-2.svg', collapsed: false, collapsible:false,
        background: '0x55ffd23d')

treeNode('Business-activities.treeNode', rendered: 'activityId',
        icon: 'addto-32x32.png', collapsed: false)
```

Here is the screenshot :
![image](https://user-images.githubusercontent.com/4968224/46656292-fda48b00-cbad-11e8-8113-78bde7fa415a.png)

**Comment by vvandens** [comment]
Collapsible: (true|false) and collapsed: (true|false) is not for tree views. It rules the titled border header behaviour.
All other issues fixed.
