### ISSUE TITLE
Hibernate HBM descriptors have issue with "aBcDef"  named like properties

### ISSUE THREAD

**Issue by Dealus** [jspresso/jspresso-ce#62]
When an entity has a property that starts with a lower case character immediately followed by an upper case one, the HBM generated property starts with an uppercase character.

Example:
```groovy
Entity('MyEntity') {
 string_11 "mYproperty"
}
```
Generates MyEntity.hbm.xml containing
```xml
<property name="MYproperty">
  <column name="M_Y_PROPERTY" length="11" not-null="true"/>
</property>
```
I used the fix-hibernate-descriptors goal to deal with the problem, but it seems that the regexp engine that is used is limited and does not provide any mean to change a character's case.

For now, the only thing I can do is:
```xml
 <replaceregexp byline="true" flags="mg" preserveLastModified="true">
  <regexp pattern="property name=&quot;M(.*)$" />
  <substitution expression="property name=&quot;m\1" />
  <fileset dir="${xdoclet.dest}">
    <include name="**/*.hbm.xml" />
  </fileset>
</replaceregexp>
```
Which doesn't solve the issue, as hibernate will then convert the M_Y_PROPERTY to MYproperty and will search for it within the MyEntity.class

**Comment by vvandens** [comment]
What problem do you have when letting the generated hibernate hbm.xml untouched ?

**Comment by vvandens** [comment]
By the way, this conforms to the JavaBean standard, i.e. `mYproperty` generates `get/setMYproperty()` setters, which, in terms of JavaBean standard corresponds to `MYproperty` property.
Jspresso does its best to deal with this case and performs necessary transformations do deal with the ambiguity between `mYproperty` and `MYproperty`.

**Comment by Dealus** [comment]
'''
However, there is one case where these transformations are missing when constructing a restriction on this kind of property. I generates an Hibernate exception.
'''

That's exactly the issue I had, sorry for the misleading analysis... And thx
