### ISSUE TITLE
Missing method addAllToCollection

### ISSUE THREAD

**Issue by ftemplier** [jspresso/jspresso-ce#64]
Add a method addAllToCollection to avoid issues when we want add a huge quantity of entities in a collection.
Today we can only add entity one by one or create a collection with all entities and set it on entity with collection.

**Comment by vvandens** [comment]
The API for manipulating collection properties already offers an optimized bulk update method allowing to replace the entire property, i.e. `setXXX(collection)`. It will perform a diff and optimize notifications.
In few lines you can have the same behavior than `addAllToXXX()` :

```
Set<?> coll = new HashSet<>(entity.getXXX());
coll.addAll(elements);
entity.setXXX(coll);
```

This way, you can easily implement an `addAll(i, coll)`, `removAll(coll)`, and so on.
