### ISSUE TITLE
Asynchronous controller preference store if not using the correct preference path 

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#654]
The controller dedicated to asynchronous action should "inherit" the main controller preference store

**Comment by vvandens** [comment]
The preference store is correctly set but there was an issue that removed the application session content (and then its subject) from the slave controller(s) when the user disconnects from the application.
It should be fixed by #651 
Can you check ?

**Comment by vvandens** [comment]
It's not a duplicate. The slave controller user preference path is actually missing.
