### ISSUE TITLE
ActionMap on table's property view no more visible when using dots

### ISSUE THREAD

**Issue by maximehamm** [jspresso/jspresso-ce#672]
The action map is not visible for table's property view... when the property view's name contains a reference to child field

Here is the use case. The action map should ne visible for all Xn properties:

```
table('IComputation.nolink.view', readOnly: true, itemSelectionAction: 'loadExtraComputationAction') {
    columns {
        propertyView name: 'reportMarkers', paramSets: ['error.report']
        propertyView name: 'computationType.code', i18nNameKey: 'X0', actionMap: 'displayComputationDocumentationActionMap', readOnly: true
        propertyView name: 'computationType.code', i18nNameKey: 'X1', actionMap: 'loginActionMap', readOnly: true
        propertyView name: 'computationType.code', i18nNameKey: 'X2', actionMap: 'loginActionMap'
        propertyView name: 'computationType', i18nNameKey: 'X3', actionMap: 'loginActionMap', readOnly: true
        propertyView name: 'computationType', i18nNameKey: 'X4', actionMap: 'loginActionMap'
        propertyView name: 'totalCost', horizontalAlignment: 'RIGHT'
    }
}
```

Here is the rendering (the action map is only visible for properties X3 and X4 which have no "dot") :
<img width="644" alt="image" src="https://user-images.githubusercontent.com/4968224/59664751-ee9cc080-91b1-11e9-8509-139a05d5a7de.png">

**Comment by vvandens** [comment]
The problem was not about the dot notation but about the enumeration type cell renderers that did not support action maps. This is fixed.
